<a href="https://colab.research.google.com/github/DurhamARC/openpose-music/blob/master/OpenPose_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pose Detection with OpenPose

This notebook uses an open source project [CMU-Perceptual-Computing-Lab/openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose.git) to detect/track multi person poses on a given youtube video.

For other deep-learning Colab notebooks, visit [tugstugi/dl-colab-notebooks](https://github.com/tugstugi/dl-colab-notebooks).


## Install OpenPose

In [0]:
import os
from os.path import exists, join, basename, splitext

git_repo_url = 'https://github.com/CMU-Perceptual-Computing-Lab/openpose.git'
project_name = splitext(basename(git_repo_url))[0]
!rm -rf openpose
if not exists(project_name):
  # see: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/949
  # install new CMake becaue of CUDA10
  !wget -q https://cmake.org/files/v3.17/cmake-3.17.2-Linux-x86_64.tar.gz
  !tar xfz cmake-3.17.2-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local
  # clone openpose
  !git clone -q --depth 1 $git_repo_url
  # --recursive necessary in the line below, as otherwise you can (sometimes) get "lpthreads" errors in cmake ("undefined reference to `pthread_create'" etc). See, for example, https://github.com/facebookarchive/caffe2/issues/1234
  !sed -i 's/execute_process(COMMAND git checkout --recursive master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/execute_process(COMMAND git checkout f019d0dfe86f49d1140961f8c7dec22130c83154 WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/g' openpose/CMakeLists.txt
  # install system dependencies
  !apt-get -qq install -y libatlas-base-dev libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler libgflags-dev libgoogle-glog-dev liblmdb-dev opencl-headers ocl-icd-opencl-dev libviennacl-dev
  # build openpose
  !cd openpose && rm -rf build || true && mkdir build && cd build && cmake -DBUILD_PYTHON=ON .. && make -j`nproc`



In [6]:
!pwd
print("Running Python API example.")
print("The imshow command in that example will lead to a 'cannot connect to X server' error in the end, which can be supressed by changing it to imwrite, for example.")
!cd openpose/build/examples/tutorial_api_python && python3 01_body_from_image.py
print("Another example.")
!cd openpose/build/examples/tutorial_api_python && python3 06_face_from_image.py

/content
Running Python API example.
The imshow command in that example will lead to a 'cannot connect to X server' error in the end, which can be supressed by changing it to imwrite, for example.
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Body keypoints: 
[[[3.2809854e+02 2.1974371e+02 7.5993967e-01]
  [3.2289130e+02 2.1718504e+02 8.3385360e-01]
  [2.9802701e+02 2.2368245e+02 8.8920242e-01]
  [2.7715598e+02 2.5109933e+02 8.6595273e-01]
  [2.9809534e+02 2.7328116e+02 8.2083827e-01]
  [3.4900360e+02 2.1327135e+02 9.2912471e-01]
  [3.6726160e+02 2.3550529e+02 8.7097746e-01]
  [3.6850781e+02 2.6154324e+02 8.3065987e-01]
  [3.2806213e+02 2.8759146e+02 8.6716896e-01]
  [3.1245990e+02 2.8764346e+02 7.8310686e-01]
  [3.2936475e+02 3.3851541e+02 8.6039579e-01]
  [3.3854834e+02 3.9202173e+02 7.7205557e-01]
  [3.3985031e+02 2.8631238e+02 8.6554557e-01]
  [3.4376807e+02 3.3462039e+02 7.7605212e-01]
  [3.4638205e+0

## Detect poses on a test video

Connect to Google Drive to access files on which to detect poses.

In [0]:
from google.colab import drive
drive.mount('/content/drive')
!ls '/content/drive/My Drive/Videos'

Download the above youtube video, cut the first 5 seconds and do the pose detection on that 5 seconds:

In [0]:
!rm -rf video.mp4
# cut the first 5 seconds
!ffmpeg -y -loglevel info -i "/content/drive/My Drive/Videos/NIR_VS_Bhoop_CentralClose_StereoMix.mp4" -t 5 video.mp4
# detect poses on the these 5 seconds
!rm -f openpose.avi
!cd openpose && ./build/examples/openpose/openpose.bin --video ../video.mp4 --write_json ./output/ --display 0 --part-candidates --write_video ../openpose.avi
# convert the result into MP4
!ffmpeg -y -loglevel info -i openpose.avi output.mp4

Finally, visualize the result:

In [0]:
import numpy as np
import os
import cv2
import json
print('OpenCV - version: ',cv2.__version__)
import pandas as pd

# video file
cap = cv2.VideoCapture('video.mp4')

def get_vid_properties(): 
    width = int(cap.get(3))  # float
    height = int(cap.get(4)) # float
    cap.release()
    return width,height
  
print('Video Dimensions: ',get_vid_properties())

# Load keypoint data from JSON output
column_names = ['x', 'y', 'acc']

# Paths - should be the folder where Open Pose JSON output was stored
path_to_json = "openpose/output/"

# Import Json files, pos_json = position JSON
json_files = [pos_json for pos_json in os.listdir(path_to_json) if pos_json.endswith('.json')]
print('Found: ',len(json_files),'json keypoint frame files')
count = 0

width,height = get_vid_properties()

# instanciate dataframes 
body_keypoints_df = pd.DataFrame()
left_shoulder_df = pd.DataFrame()
left_elbow_df = pd.DataFrame()

print('json files: ',json_files[0])   

# Loop through all json files in output directory
# Each file is a frame in the video
# If multiple people are detected - choose the most centered high confidence points
for file in json_files:

    temp_df = json.load(open(path_to_json+file))
    temp = []
    for k,v in temp_df['part_candidates'][0].items():
        
        # Single point detected
        if len(v) < 4:
            temp.append(v)
            #print('Extracted highest confidence points: ',v)
            
        # Multiple points detected
        elif len(v) > 4: 
            near_middle = width
            np_v = np.array(v)
            
            # Reshape to x,y,confidence
            np_v_reshape = np_v.reshape(int(len(np_v)/3),3)
            np_v_temp = []
            # compare x values
            for pt in np_v_reshape:
                if(np.absolute(pt[0]-width/2)<near_middle):
                    near_middle = np.absolute(pt[0]-width/2)
                    np_v_temp = list(pt)
         
            temp.append(np_v_temp)
            #print('Extracted highest confidence points: ',np_v_temp)
        else:
            # No detection - record zeros
            temp.append([0,0,0])
            
    temp_df = pd.DataFrame(temp)
    temp_df = temp_df.fillna(0)
    #print(temp_df)

    try:
        prev_temp_df = temp_df
        body_keypoints_df= body_keypoints_df.append(temp_df)
        left_shoulder_df = left_shoulder_df.append(temp_df.iloc[5].astype(int))
        left_elbow_df = left_elbow_df.append(temp_df.iloc[6].astype(int))

    except:
        print('bad point set at: ', file)
        
body_keypoints_df.columns = column_names
left_shoulder_df.columns = column_names
left_elbow_df.columns = column_names

body_keypoints_df.reset_index()
left_shoulder_df = left_shoulder_df.reset_index(drop = True)
left_elbow_df = left_elbow_df.reset_index(drop = True)

print('length of merged keypoint set: ',body_keypoints_df.size)

print(left_shoulder_df.head())
print(left_elbow_df.head())

In [0]:
# Drawing the green box that shows the bar centered over the foot
# pts is in the form [x,y,confidence], for this we only need the first 2 columns [x,y]
# img is the image or frame we're drawing to
def draw_bar_box(img, shoulder_pt, elbow_pt, color_select = (255,255,255)):
    fudge_fact = 20
    shoulder_x = int(np.mean(shoulder_pt['x']))-15
    elbow_x = int(np.mean(elbow_pt['x']))+15
    print(shoulder_x, elbow_x)
    top = 0
    base = height
    
    # call the open cv rectangle function
    cv2.rectangle(img, (shoulder_x,top), (elbow_x, base), color_select, -1)
    
# Drawing a poly-line, a line connecting mutiple nodes
# pts is in the form [x,y,confidence], for this we only need the first 2 columns [x,y]
# img is the image or frame we're drawing to
def draw_poly_line(img, pts, color_select = (255,255,255), thick = 2):
    poly_line_thickness = thick
    poly_closed = False
    pts = pts[:,0:2]
    pts = pts.reshape((-1,1,2))
    
    # call the open cv poly line function
    cv2.polylines(img, np.int32([pts]), poly_closed, color_select, thickness=poly_line_thickness)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow

cap = cv2.VideoCapture('video.mp4')
i = 0

while(cap.isOpened()):
    ret, frame = cap.read()
    print(left_shoulder_df.iloc[i])
    draw_bar_box(frame, left_shoulder_df.iloc[i], left_elbow_df.iloc[i])

    cv2_imshow(frame)
    i += 1
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()



In [0]:
def show_local_mp4_video(file_name, width=640, height=480):
  import io
  import base64
  from IPython.display import HTML
  video_encoded = base64.b64encode(io.open(file_name, 'rb').read())
  return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                        <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                      </video>'''.format(width, height, video_encoded.decode('ascii'))) 

show_local_mp4_video('output.mp4', width=960, height=720)